# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40b23d27e1c5dab4a476d32a390f289cb260fc4546c6beffb7fa39f643625acbd7bef90a4fedebf4eb059c462ab6a008fac6508520aeb1ed2c8ca1c3902c7ff0

test:
  secret_key_base: 96f1eb58f191093ad18b0f23de71355941600d8bd39b54109a2a1bd37c72229ace92f146833b04be2071e94b08c7bb87ee2872e0c507f6654c1418a39104a19c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
